language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
install:
- pip install ./schema_salad
- pip install nose codecov coverage
script:
- nosetests --with-coverage --cover-package=cwlpy
after_success:
- codecov
